#!/bin/bash
# this file will modify the result file generated by gromac
# to the form of the following:
# time  x  y  z
# 0    0   0   0

# fileName="msdRes.txt"
fileName="text.txt"
ignoreChar=('#' '@')
while IFS= read -r line; do
    if [[ ${line} =~ ^@.* | ^\#.* ]]
    then
        echo "starts with @"
        echo ${line}
    fi
done < ${fileName}